/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSegmentsRouteImport } from './routes/_app.segments'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCustomersRouteImport } from './routes/_app.customers'
import { Route as AppCampaignsRouteImport } from './routes/_app.campaigns'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppAiRouteImport } from './routes/_app.ai'
import { Route as AppCampaignsIdRouteImport } from './routes/_app.campaigns.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSegmentsRoute = AppSegmentsRouteImport.update({
  id: '/segments',
  path: '/segments',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsRoute = AppCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAiRoute = AppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AppRoute,
} as any)
const AppCampaignsIdRoute = AppCampaignsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCampaignsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ai': typeof AppAiRoute
  '/analytics': typeof AppAnalyticsRoute
  '/campaigns': typeof AppCampaignsRouteWithChildren
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/segments': typeof AppSegmentsRoute
  '/campaigns/$id': typeof AppCampaignsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/ai': typeof AppAiRoute
  '/analytics': typeof AppAnalyticsRoute
  '/campaigns': typeof AppCampaignsRouteWithChildren
  '/customers': typeof AppCustomersRoute
  '/dashboard': typeof AppDashboardRoute
  '/segments': typeof AppSegmentsRoute
  '/campaigns/$id': typeof AppCampaignsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/ai': typeof AppAiRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/campaigns': typeof AppCampaignsRouteWithChildren
  '/_app/customers': typeof AppCustomersRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/segments': typeof AppSegmentsRoute
  '/_app/campaigns/$id': typeof AppCampaignsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/ai'
    | '/analytics'
    | '/campaigns'
    | '/customers'
    | '/dashboard'
    | '/segments'
    | '/campaigns/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/ai'
    | '/analytics'
    | '/campaigns'
    | '/customers'
    | '/dashboard'
    | '/segments'
    | '/campaigns/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/ai'
    | '/_app/analytics'
    | '/_app/campaigns'
    | '/_app/customers'
    | '/_app/dashboard'
    | '/_app/segments'
    | '/_app/campaigns/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/segments': {
      id: '/_app/segments'
      path: '/segments'
      fullPath: '/segments'
      preLoaderRoute: typeof AppSegmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns': {
      id: '/_app/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof AppCampaignsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai': {
      id: '/_app/ai'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof AppAiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campaigns/$id': {
      id: '/_app/campaigns/$id'
      path: '/$id'
      fullPath: '/campaigns/$id'
      preLoaderRoute: typeof AppCampaignsIdRouteImport
      parentRoute: typeof AppCampaignsRoute
    }
  }
}

interface AppCampaignsRouteChildren {
  AppCampaignsIdRoute: typeof AppCampaignsIdRoute
}

const AppCampaignsRouteChildren: AppCampaignsRouteChildren = {
  AppCampaignsIdRoute: AppCampaignsIdRoute,
}

const AppCampaignsRouteWithChildren = AppCampaignsRoute._addFileChildren(
  AppCampaignsRouteChildren,
)

interface AppRouteChildren {
  AppAiRoute: typeof AppAiRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCampaignsRoute: typeof AppCampaignsRouteWithChildren
  AppCustomersRoute: typeof AppCustomersRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppSegmentsRoute: typeof AppSegmentsRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiRoute: AppAiRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCampaignsRoute: AppCampaignsRouteWithChildren,
  AppCustomersRoute: AppCustomersRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppSegmentsRoute: AppSegmentsRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
